### ISSUE TITLE
Are the .tmp. files really necessary ? 

### ISSUE THREAD

**Issue by kosz** [robatron/gulp-chug#12]
They are a bit annoying to manage. 

Sometimes gulp crashes and more and more tmp files get piled up. I currently write clean tasks for them and add them to git/svn ignore so they don't confuse me. But it would be nice if they weren't there at all. 

By the way thanks for this plugin. I noticed that the gulp folk blacklisted it, i'm a bit sad about that. Are you still planning on continuing updating this, given the circumstances ?

**Comment by robatron** [comment]
Hey @kosz ,

A temp file is created if the gulpfile source is a buffer, which is only necessary if you're modifying the gulpfile source stream before passing it to `gulp-chug`. 

If you're not modifying the gulpfile source stream, simply pass `{ read: false }` when `gulp.src`ing. See https://github.com/robatron/gulp-chug#make-gulp-chug-faster-by-ignoring-file-contents

> I noticed that the gulp folk blacklisted it, i'm a bit sad about that. Are you still planning on continuing updating this, given the circumstances?

I'm not planning any major upgrades since I'm not really using it anymore myself, but I'm currently happy to maintain this package for now, i.e., respond to issues and PRs.

Thanks for your interest!
